apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-consumer
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-consumer
  template:
    metadata:
      labels:
        app: todo-consumer
    spec:
      containers:
      - name: todo-consumer
        image: haykhayrapetyan09/simple-todo-app:latest
        command: ["python", "consumer.py"]
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: DB_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: RABBITMQ_PASSWORD
